version: "3.9"

services:
  frontend:
    image: ${REGISTRY_ADDRESS}/frontend:${CI_PIPELINE_ID}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ${REGISTRY_ADDRESS}/delivery_service:${CI_PIPELINE_ID}
    ports:
      - "8002:8002"
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

  database_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "d-iskandarov@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5000:80"
    links:
      - "database:pgsql-server"
    volumes:
      - pga4data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pgdata:
  pga4data:
